### ISSUE TITLE
No module named 'trackml.dataset'

### ISSUE THREAD

**Issue by arycloud** [LAL/trackml-library#12]
I have installed it directly from GitHub repo to Kaggle kernel when I import `import trackml` it's ok but when I try to import `from trackml.dataset import load_dataset` it returns `from trackml.dataset import load_dataset`.

Sorry for this shit, I'm new to Kaggle.

**Comment by msmk0** [comment]
The following procedures works for me create a installation on Kaggle:

1. Create new kernel/notebook
2. Go to settings
3. Add a custom package using `LAL/trackml-library` in the second entry field.
4. Wait for installation to finish and restart kernel.
5. Use `from trackml.dataset import load_dataset`

Could you let me know if this leads to the same result for you or if not where it breaks.

**Comment by arycloud** [comment]
Hi @msmk0 ,
It's working now, thanks a lot!

**Comment by sysuin** [comment]
How to solve the same issue in Google Colab?
