### ISSUE TITLE
Unexpected keyword in `_analyze_tracks(.)`

### ISSUE THREAD

**Issue by Kasperfred** [LAL/trackml-library#13]
Using Pandas v0.22.0 with Python v3.6, I get the following error when using the `_analyze_tracks` helper-function:

```
     29     event = pandas.merge(truth[['hit_id', 'particle_id', 'weight']],
     30                          submission[['hit_id', 'track_id']],
---> 31                          on=['hit_id'], how='left', validate='one_to_one')
     32     event.drop('hit_id', axis=1, inplace=True)
     33     event.sort_values(by=['track_id', 'particle_id'], inplace=True)

TypeError: merge() got an unexpected keyword argument 'validate'
```

According to the [Pandas source code](https://github.com/pandas-dev/pandas/blob/v0.22.0/pandas/core/reshape/merge.py#L49), the `validate` keyword is expected with the `merge(.)` function.
 
However, by simply removing the keyword from the function call, I'm able to reproduce the results of  the [DBSCAN kernel](https://www.kaggle.com/mikhailhushchyn/dbscan-benchmark/notebook
).

![image](https://user-images.githubusercontent.com/13367236/39958472-d8c28aaa-5603-11e8-9326-903876e9d558.png)

I'm not sure how relevant this is as it shouldn't be a problem for most people, but if anyone is experiencing the same issue, this may be a viable, albeit not great, solution.

**Comment by liaopeiyuan** [comment]
pandas 0.22.0 does not have the 'validate' argument in the parameters of pandas.merge(); upgrading to pandas 0.23.0 should also fix the problem.
