### ISSUE TITLE
trackml-library and GPU

### ISSUE THREAD

**Issue by dhrou** [LAL/trackml-library#8]
Noticed this post
https://www.kaggle.com/c/trackml-particle-identification/discussion/55935 

For some reason I am unable to use the GPU provided by kaggle with the trackml library. Either one works alone but none at the same time. What might be the issue?

**Comment by msmk0** [comment]
I could reproduce the issue by running a Kernel with activated GPU support and trying to install a custom library. According to the error messages I get, this problem can not be fixed from our side. When running with GPU support on Kaggle custom docker images, e.g. with the installed library, are not supported.
